version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT:-8000}:8000
    depends_on:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal

  php:
    build: ./docker/php
    image: lvivit/php-8.1
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    networks:
      - internal

  pgsql:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - pgsql-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - ${SWAGGER_PORT:-8080}:8080
    environment:
      SWAGGER_JSON: /var/www/OpenApiSpec.yaml
    volumes:
      - ./:/var/www

networks:
  internal:

volumes:
  pgsql-data:
